# Generated by Django 3.1.7 on 2021-04-20 02:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True, default='2021-04-20 02:36:27', null=True)),
                ('cid', models.CharField(auto_created=True, default='0', editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('badges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True, default='2021-04-20 02:36:27', null=True)),
                ('tid', models.CharField(auto_created=True, default='0', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('cid', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('values_scores', models.JSONField(blank=True, default=dict)),
                ('badges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('company', models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'verbose_name': 'Team',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True, default='2021-04-20 02:36:27', null=True)),
                ('uid', models.CharField(auto_created=True, default='0', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('tid', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('user_role', models.CharField(choices=[('emp', 'employee'), ('mng', 'manager'), ('adm', 'administrator')], default='emp', max_length=3)),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('profile_picture', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('values_scores', models.JSONField(blank=True, default=dict)),
                ('badges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('network', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, default=list, size=None)),
                ('team', models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True, default='2021-04-20 02:36:27')),
                ('rid', models.CharField(auto_created=True, default='0', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('uid_from', models.CharField(max_length=8)),
                ('uid_to', models.CharField(max_length=8)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('flag_count', models.IntegerField(default=0)),
                ('comments', models.CharField(blank=True, default='', max_length=120)),
                ('user_from', models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid_from', to='api.user')),
                ('user_to', models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid_to', to='api.user')),
            ],
            options={
                'verbose_name': 'Recognition',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('nid', models.CharField(auto_created=True, default='0', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('notif_uid', models.CharField(max_length=8)),
                ('notif_message', models.CharField(blank=True, default='', max_length=120)),
                ('notif_type', models.CharField(blank=True, default='', max_length=60)),
                ('seen', models.BooleanField(default=False)),
                ('notif_user', models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'verbose_name': 'Notification',
            },
        ),
    ]
