# Generated by Django 3.1.7 on 2021-03-12 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cid', models.CharField(default='1', max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8, unique=True)),
                ('values', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tid', models.CharField(default='1', max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('values_scores', models.JSONField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company')),
            ],
            options={
                'verbose_name': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(default='00000000', max_length=8)),
                ('tags', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(default='1', max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60, null=True)),
                ('password', models.CharField(max_length=120, null=True)),
                ('user_role', models.CharField(choices=[('emp', 'employee'), ('mng', 'manager'), ('dev', 'developer')], default='employee', max_length=60)),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('values_scores', models.JSONField(null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
