# Generated by Django 3.1.7 on 2021-03-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='team',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
