# Generated by Django 3.1.7 on 2021-04-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('nid', models.CharField(auto_created=True, default='0', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('notif_uid', models.CharField(max_length=8)),
                ('notif_message', models.CharField(blank=True, default='', max_length=120)),
                ('notif_user', models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'verbose_name': 'Notification',
            },
        ),
    ]
