# Generated by Django 3.1.7 on 2021-04-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_picutre',
            new_name='profile_picture',
        ),
    ]
