# Generated by Django 3.1.7 on 2021-03-20 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='user_from',
            field=models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userid_from', to='api.user'),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='user_to',
            field=models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userid_to', to='api.user'),
        ),
    ]
