# Generated by Django 3.1.7 on 2021-03-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='created_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='recognition',
            old_name='created_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='created_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='date_created',
        ),
    ]
