# Generated by Django 3.1.7 on 2021-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='values',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='team',
            name='values_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='values_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
