# Generated by Django 3.1.7 on 2021-03-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210312_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cid',
            field=models.CharField(default='37621272', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='tid',
            field=models.CharField(default='76404464', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='16682592', max_length=8, primary_key=True, serialize=False),
        ),
    ]
