# Generated by Django 3.1.7 on 2021-04-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210405_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
