# Generated by Django 3.1.7 on 2021-03-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210326_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='flag_count',
            field=models.IntegerField(default=0),
        ),
    ]
