# Generated by Django 3.1.7 on 2021-04-09 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210409_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 9, 19, 19, 31, 180133, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 9, 19, 19, 31, 183079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 9, 19, 19, 31, 180792, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 9, 19, 19, 31, 181770, tzinfo=utc), null=True),
        ),
    ]
