# Generated by Django 3.1.7 on 2021-03-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
        migrations.AddField(
            model_name='user',
            name='tid',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
