# Generated by Django 3.1.7 on 2021-03-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210312_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote'},
        ),
        migrations.AddField(
            model_name='vote',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='vote',
            name='uid_from',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AddField(
            model_name='vote',
            name='uid_to',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AlterField(
            model_name='company',
            name='cid',
            field=models.CharField(default='43438467', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='tid',
            field=models.CharField(auto_created=True, default='96089188', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(auto_created=True, default='18340175', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='tags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vid',
            field=models.CharField(auto_created=True, default='06460909', max_length=8),
        ),
    ]
