# Generated by Django 3.1.7 on 2021-03-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210312_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cid',
            field=models.CharField(default='47676224', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='values',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='team',
            name='tid',
            field=models.CharField(auto_created=True, default='34305813', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='values_scores',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(auto_created=True, default='99570922', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vid',
            field=models.CharField(auto_created=True, default='58241020', max_length=8),
        ),
    ]
