# Generated by Django 3.1.7 on 2021-03-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
