# Generated by Django 3.1.7 on 2021-04-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210425_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avt5362145.png', null=True, upload_to='images/'),
        ),
    ]
