# Generated by Django 3.1.7 on 2021-04-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210425_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avt7352373.png', null=True, upload_to='images/'),
        ),
    ]
