# Generated by Django 3.1.7 on 2021-03-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210313_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cid',
            field=models.CharField(default='09250882', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tid',
            field=models.CharField(auto_created=True, default='39147270', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(auto_created=True, default='59572269', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vid',
            field=models.CharField(auto_created=True, default='35848530', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
