# Generated by Django 3.1.7 on 2021-03-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210313_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cid',
            field=models.CharField(default='62812427', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tid',
            field=models.CharField(auto_created=True, default='57701474', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(auto_created=True, default='90022075', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vid',
            field=models.CharField(auto_created=True, default='47690036', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
