# Generated by Django 3.1.7 on 2021-04-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210426_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avt3613851.png', null=True, upload_to='images/'),
        ),
    ]
