# Generated by Django 3.1.7 on 2021-03-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210308_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='TeamBlankSpace', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(auto_created=True, default='0', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
