from django.db import models
import api.models.constant as const
from .Company import *
from api.helpers.create_unique_id import create_unique_id
import uuid

"""
Team object model

Required field
    company
    name

Optional field
    tid
    values_scores
"""
class Team(models.Model):

    # refer to Company object model as primary key
    company = models.ForeignKey(
        Company,
        on_delete = models.SET_NULL,
        null=True
    )

    # team id (required, unique, autogenerated)
    tid = models.CharField(
        primary_key=True,
        max_length=const.ID_LEN,
        default=create_unique_id(len=const.ID_LEN),
        auto_created=True,
        unique=True,
        editable=False,
    )


    # team name (required, unique)
    name = models.CharField(
        max_length=const.CHARFIELD_SHORT_LEN,
        unique=True,
        blank=False
    )

    # scores on company corporate values
    values_scores = models.JSONField(
        default={}
    )

    class Meta:
        verbose_name = "Team"
