version: '3.7'

services:
  db:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=whitespace
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - whitespace-db-data:/var/lib/postgresql/data/pgdata

  api-server:
    build:
      context: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/code
    environment: 
      - WHITESPACE_LOCAL=true
    env_file: 
      - ./backend/.env
    ports:
      - 8000:8000
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh db:5432 -- python manage.py makemigrations
        python manage.py migrate
        python manage.py loaddata company.json 
        python manage.py loaddata teams.json 
        python manage.py loaddata users.json 
        python manage.py runserver 0.0.0.0:8000

volumes:
  whitespace-db-data:
