version: '3.7'

services:
  api-server:
    build:
      context: ./backend
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
  
  frontend-webpage:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
