version: '3.7'

services:
  api-server:
    build:
      context: ./backend
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000